version: "3.8"
services:
    api:
      container_name: ecollector-api-dev
      build:
        context: ./api
        target: development
        dockerfile: ./Dockerfile
      command: yarn start:debug
      ports:
        - "3000:3000"
        - "9229:9229"
      depends_on:
        - postgres
      restart: unless-stopped
      volumes:
        - ./api:/usr/src/app
        - /usr/api/src/app/node_modules

    postgres:
      image: postgres
      container_name: ecollector-postgres-dev
      restart: unless-stopped
      working_dir: /application
      volumes:
        - postgres-dev:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DB:-ecollector-dev}
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      ports:
        - "5432:5432"
    pgadmin:
      image: dpage/pgadmin4
      container_name: ecollector-pgadmin-dev
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-user@example.com}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-pass}
      ports:
        - "5433:80"
    mailhog:
      image: mailhog/mailhog:latest
      container_name: ecollector-mailhog-dev
      ports:
        - "8025:8025"
volumes:
  postgres-dev:
