version: "3.8"
services:
  client:
    container_name: ecollector-prod-client
    build:
      context: ./frontend
      target: production
      dockerfile: Dockerfile
    env_file:
      - .config/.env.prod
    ports:
      - "4000:4000"

  server:
    container_name: ecollector-prod-server
    build:
      context: ./api
      target: production
      dockerfile: Dockerfile
    env_file:
      - .config/.env.prod
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./.data/prod/uploads:/usr/src/api/uploads

  postgres:
    image: postgres:14.1
    container_name: ecollector-prod-postgres
    restart: on-failure
    working_dir: /application
    ports:
      - "5432:5432"
    volumes:
      - ./.data/prod/postgres-data:/var/lib/postgresql/data
    env_file:
      - .config/.env.prod

#    pgadmin:
#      image: dpage/pgadmin4
#      container_name: ecollector-pgadmin
#      environment:
#        - PGADMIN_DEFAULT_EMAIL=user@example.com
#        - PGADMIN_DEFAULT_PASSWORD=pass
#      ports:
#        - "5433:80"
#    mailhog:
#      image: mailhog/mailhog:latest
#      container_name: ecollector-mailhog
#      ports:
#        - "8025:8025"
