version: "3.8"
services:
    app:
      container_name: ecollector-app
      ports:
        - "3000:3000"
      depends_on:
        - postgres
    postgres:
      image: postgres
      container_name: ecollector-postgres
      restart: unless-stopped
      working_dir: /application
      volumes:
        - postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_DB=ecollector-dev
        - POSTGRES_USER=user
      ports:
        - "5432:5432"
#    pgadmin:
#      image: dpage/pgadmin4
#      container_name: ecollector-pgadmin
#      environment:
#        - PGADMIN_DEFAULT_EMAIL=user@example.com
#        - PGADMIN_DEFAULT_PASSWORD=pass
#      ports:
#        - "5433:80"
#    mailhog:
#      image: mailhog/mailhog:latest
#      container_name: ecollector-mailhog
#      ports:
#        - "8025:8025"
volumes:
  postgres:
