version: "3.8"
services:
  api_server:
    container_name: ecollector-api-dev
    build:
      context: ./api
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - "9229:9229"
      - "3000:3000"
    env_file:
      - .config/.env.dev
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./api/:/usr/src/api
      - /usr/src/api/node_modules

  postgres:
    container_name: ecollector-postgres-dev
    image: postgres:13.4
    restart: unless-stopped
    working_dir: /application
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .config/.env.dev

  pgadmin:
    links:
      - postgres:postgres
    container_name: ecollector-pgadmin-dev
    image: dpage/pgadmin4
    env_file:
      - .config/.env.dev
    depends_on:
      - postgres
    volumes:
      - /data/pgadmin:/root/.pgadmin

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ecollector-nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "8080:80"
    depends_on:
      - api_server
    env_file:
      - .config/.env.dev

#    mailhog:
#      image: mailhog/mailhog:latest
#      container_name: ecollector-mailhog-dev
#      ports:
#        - "8025:8025"
