name: Build api

on:
  push:
    branches: [ master ]
    paths:
      - api/*
  pull_request:
    branches: [ master ]
    paths:
      - api/*
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the api Docker image
      run: docker build ./api/ --file Dockerfile --tag ecollector-api:$(date +%s)
